Bugfix/zcs 1469
Zimbra/zm-certificate-manager-store pull request #2
Opened 2017-12-11 07:19 UTC by haitran1696

@silentsakky Please help me to review the code

2017-12-11 07:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-certificate-manager-store?pullRequest=2) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-certificate-manager-store?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-certificate-manager-store?pullRequest=2) it.</sub>

2017-12-11 10:34 UTC, fatkudu approved these changes
You could squash these 2 changes before merging perhaps.

2017-12-11 15:17 UTC, plobbes commented on src/java/com/zimbra/cert/GetCert.java
> +    final static String [] CERT_TYPES = {"imapd","ldap", "mailboxd", "mta", "proxy"};
nit: space after ','

2017-12-12 12:17 UTC, silentsakky approved these changes

2017-12-12 14:05 UTC, fatkudu requested changes
Please squash the commits.  We really don't need 3 commits for this small change.

2017-12-15 21:03 UTC, grishick commented
@haitran1696 please e-sign the CLA

2017-12-18 06:36 UTC, bluesea1696 commented
@grishick I signed the CLA but I see that license/cla is not signed yet. 
<img width="1263" alt="sign cla" src="https://user-images.githubusercontent.com/20589204/34092907-3f710dcc-e3f8-11e7-83e1-7ac93c8b918b.png">
<img width="698" alt="cla" src="https://user-images.githubusercontent.com/20589204/34092932-5ae08c68-e3f8-11e7-9963-2e64c8089497.png">

2017-12-18 06:49 UTC, haitran1696 commented
@grishick I have signed the CLA but the status is still pending. I also rechecked it. 
<img width="1263" alt="sign cla" src="https://user-images.githubusercontent.com/34335589/34093320-20b9e91a-e3fa-11e7-9627-0bdf86a10517.png">
<img width="698" alt="cla" src="https://user-images.githubusercontent.com/34335589/34093329-288e3a1a-e3fa-11e7-8f4c-5be56f501d95.png">

2018-01-16 06:46 UTC, haitran1696 commented
Hi @grishick, I signed the CLA successfully

2018-01-16 08:54 UTC, fatkudu approved these changes

2018-01-16 13:59 UTC, plobbes approved these changes

2018-01-16 14:46 UTC, gordyt approved these changes

2018-01-17 23:12 UTC, grishick approved these changes

2018-02-13 06:08 UTC, silentsakky approved these changes

2019-07-24 13:07 UTC, silentsakky commented
Ticket closed as Won't Fix

2019-07-24 13:07 UTC, closed without merging